/*
 * Elysme - https://github.com/TheEntropyShard/Elysme
 * Copyright (C) 2026 TheEntropyShard
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package me.theentropyshard.elysme.deltachat.rpc;

public enum RpcMethod {
    sleep,
    check_email_validity,
    get_system_info,
    get_next_event,
    add_account,
    migrate_account,
    remove_account,
    get_all_account_ids,
    select_account,
    get_selected_account_id,
    set_accounts_order,
    get_all_accounts,
    start_io_for_all_accounts,
    stop_io_for_all_accounts,
    background_fetch,
    stop_background_fetch,
    start_io,
    stop_io,
    get_account_info,
    get_push_state,
    get_account_file_size,
    get_provider_info,
    is_configured,
    get_info,
    get_storage_usage_report_string,
    get_blob_dir,
    get_migration_error,
    copy_to_blob_dir,
    set_config,
    batch_set_config,
    set_config_from_qr,
    check_qr,
    get_config,
    batch_get_config,
    set_stock_strings,
    configure,
    add_or_update_transport,
    add_transport,
    add_transport_from_qr,
    list_transports,
    delete_transport,
    stop_ongoing_process,
    export_self_keys,
    import_self_keys,
    get_fresh_msgs,
    get_fresh_msg_cnt,
    get_next_msgs,
    wait_next_msgs,
    estimate_auto_deletion_count,
    initiate_autocrypt_key_transfer,
    continue_autocrypt_key_transfer,
    get_chatlist_entries,
    get_similar_chat_ids,
    get_chatlist_items_by_entries,
    get_full_chat_by_id,
    get_basic_chat_info,
    accept_chat,
    block_chat,
    delete_chat,
    get_chat_encryption_info,
    get_chat_securejoin_qr_code,
    get_chat_securejoin_qr_code_svg,
    secure_join,
    secure_join_with_ux_info,
    leave_group,
    remove_contact_from_chat,
    add_contact_to_chat,
    get_chat_contacts,
    get_past_chat_contacts,
    create_group_chat,
    create_group_chat_unencrypted,
    create_broadcast_list,
    create_broadcast,
    set_chat_name,
    set_chat_profile_image,
    set_chat_visibility,
    set_chat_ephemeral_timer,
    get_chat_ephemeral_timer,
    add_device_message,
    marknoticed_chat,
    get_first_unread_message_of_chat,
    set_chat_mute_duration,
    is_chat_muted,
    markseen_msgs,
    get_message_ids,
    get_existing_msg_ids,
    get_message_list_items,
    get_message,
    get_message_html,
    get_messages,
    get_message_notification_info,
    delete_messages,
    delete_messages_for_all,
    get_message_info,
    get_message_info_object,
    get_message_read_receipts,
    download_full_message,
    search_messages,
    message_ids_to_search_results,
    save_msgs,
    get_contact,
    create_contact,
    create_chat_by_contact_id,
    block_contact,
    unblock_contact,
    get_blocked_contacts,
    get_contact_ids,
    get_contacts,
    get_contacts_by_ids,
    delete_contact,
    change_contact_name,
    get_contact_encryption_info,
    lookup_contact_id_by_addr,
    parse_vcard,
    import_vcard,
    import_vcard_contents,
    make_vcard,
    set_draft_vcard,
    get_chat_id_by_contact_id,
    get_chat_media,
    export_backup,
    import_backup,
    provide_backup,
    get_backup_qr,
    get_backup_qr_svg,
    get_backup,
    maybe_network,
    get_connectivity,
    get_connectivity_html,
    get_locations,
    send_webxdc_status_update,
    send_webxdc_realtime_data,
    send_webxdc_realtime_advertisement,
    leave_webxdc_realtime,
    get_webxdc_status_updates,
    get_webxdc_info,
    get_webxdc_href,
    get_webxdc_blob,
    set_webxdc_integration,
    init_webxdc_integration,
    place_outgoing_call,
    accept_incoming_call,
    end_call,
    call_info,
    ice_servers,
    get_http_response,
    forward_messages,
    forward_messages_to_account,
    resend_messages,
    send_sticker,
    send_reaction,
    get_message_reactions,
    send_msg,
    send_edit_request,
    can_send,
    save_msg_file,
    remove_draft,
    get_draft,
    misc_get_sticker_folder,
    misc_save_sticker,
    misc_get_stickers,
    misc_send_text_message,
    misc_send_msg,
    misc_set_draft,
    misc_send_draft;

    public RpcRequest makeRequest() {
        return new RpcRequest(this.name());
    }

    public RpcRequest makeRequest(int id) {
        return new RpcRequest(id, this.name());
    }
}
